[package]
name = "pushwasm"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.21"
clap = { version = "4.2", features = ["derive"] }
mysql = "23.0"
rpassword = "7.2"
url = "2.3"
